In [209]:
import pandas as pd
import numpy as np

In [210]:
campaign = pd.read_csv('data/AMSCampaign.csv')
campaign_details = pd.read_csv('data/AMSCampaignDetail.csv')

target = pd.read_csv('data/AMSTarget.csv')
target_placement = pd.read_csv('data/AMSTargetPlacementDetail.csv')

placement = pd.read_csv('data/AMSPlacement.csv')

ad_group = pd.read_csv('data/AMSAdGroup.csv')
ad_group_details = pd.read_csv('data/AMSAdGroupDetail.csv')

search = pd.read_csv('data/AMSSearch.csv')
search_details = pd.read_csv('data/AMSSearchDetail.csv')

In [211]:
#Add campaign ID to ad groups
ad_group_details = ad_group_details.join(ad_group.set_index('id'), on='ad_groups')
ad_group_details = ad_group_details.drop(['name'], axis=1)
ad_group_details = ad_group_details.join(campaign.set_index('id'), on='campaign')

In [212]:
#add target terms and placement terms to target_placement details
target_placement = target_placement.join(target.set_index('id'), on='target')
target_placement = target_placement.rename(columns={"term": "target_term", "match_type": "target_match_type"})
placement = placement.rename(columns={"placement": "placement_type"})
placement = placement.drop(['campaign'], axis=1)
target_placement = target_placement.join(placement.set_index('id'), on = 'placement')

In [213]:
#add details to search 
search = search.join(target.set_index('id'), on='target')
search_details = search_details.join(search.set_index('id'), on='search')
search_details = search_details.rename(columns={"term": "target_term", "match_type": "target_match_type"})

In [214]:
#all events for one product
B002UVKMVY = ad_group_details[ad_group_details.asin == 'B002UVKMVY'].sort_values(by = ['sales'], ascending = False)

In [9]:
#choose one product
product = 'B001G7PQM8'

#find all ad groups for this product
product_ad_groups = ad_group_details[ad_group_details.asin == product].ad_groups.unique()

#find all campaigns with those ad groups
camps = []
for i in product_ad_groups:
    campaign_num = ad_group[ad_group.id == i].campaign.values
    #np.insert(b, campaign_num)
    camps.append(campaign_num)
product_campaigns = set(np.array(camps).flatten())

In [12]:
ad_group[ad_group.id == 1].campaign.values

array([1240])

In [229]:
product_campaigns

{1231, 1234, 1239, 1240, 2042, 3284, 55306, 170649, 172418}

In [230]:
product_ad_groups

array([    1,   196,   216,   255,  2504,  4606,  4879,  4901,  4938,
        4975,  6273,  6295,  8042, 10067])

In [231]:
product_target = []
for camp in product_campaigns:
    target_term = target[target.campaign == camp].term.values
    product_target.append(target_term)

In [237]:
target[target.campaign == 1231].term

1977    8 oz hand sanitizer with pump
1978    8 oz hand sanitizer with pump
1979    8 oz hand sanitizer with pump
1980               8oz hand sanitizer
1981               8oz hand sanitizer
                    ...              
2291              unscented hand soap
2292              unscented hand soap
2293             vegan hand sanitizer
2294             vegan hand sanitizer
2295             vegan hand sanitizer
Name: term, Length: 319, dtype: object

In [226]:
campaign_num = ad_group[ad_group.id == 255].campaign.values
campaign_num

array([1234])